name: 🔁 Sync DSN HTML to gh-pages

on:
  push:
    branches:
      - main
    paths:
      - DSN_trigger.html
      - DSNweb.v04.html
      - DSNdashboards.v04.html
      - DSNmap.v04.html
      - DS-SoAZ-logo.jpg
      - Kit-Peak-Comet-Banner.jpg

jobs:
  sync-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy files to gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin gh-pages
          git switch gh-pages
          git restore --source=main DSN_trigger.html DSNweb.v04.html DSNdashboards.v04.html DSNmap.v04.html DS-SoAZ-logo.jpg Kit-Peak-Comet-Banner.jpg
          git add DSN_trigger.html DSNweb.v04.html DSNdashboards.v04.html DSNmap.v04.html DS-SoAZ-logo.jpg Kit-Peak-Comet-Banner.jpg
          git commit -m "🔁 Auto-sync selected files from main" || echo "Nothing to commit"
          git push origin gh-pages